# Enable if maintenance mode.
# [[redirects]]
#   from = "/*"
#   to = "https://backup.atproducts.xyz/maintenance"
#   status = 301
#   force = true
#   conditions = {Language = ["en"], Country = ["US"]}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = '''
      max-age=31536000; 
      includeSubDomains; 
      preload'''
    Content-Security-Policy = '''
      default-src 'none'; 
      frame-src 'self'; 
      form-action 'self'; 
      base-uri 'self'; 
      manifest-src 'self'; 
      font-src 'self' https://cdn.jsdelivr.net https://*.cloudfront.net; 
      object-src 'self'; 
      script-src 'unsafe-inline' 'self' https://cdn.jsdelivr.net https://*.cloudfront.net; 
      style-src 'unsafe-hashes' 'self' https://cdn.jsdelivr.net https://*.cloudfront.net 'unsafe-inline'; 
      img-src 'self' data: https://*.cloudfront.net;
      frame-ancestors 'self' '''
    Features-Policy = "document-domain 'self';"
    Permissions-Policy = '''
      fullscreen=(self), 
      geolocation=(), 
      camera=(), 
      browsing-topics=(), 
      picture-in-picture=(self), 
      payment=(), 
      fullscreen=(self), 
      autoplay=(self), 
      encrypted-media=(self), 
      interest-cohort=(), 
      user-id=()'''
    Referrer-Policy = "same-origin"
